# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "chore(pre-commit.ci): auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "chore(pre-commit.ci): pre-commit autoupdate"
  autoupdate_schedule: "monthly"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
        exclude: ^cot-cli/src/project_template/
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.0
    hooks:
      - id: yamlfmt
        types_or: [json, yaml]
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        files: ^.*\.(rs|toml)$
        exclude: ^cot-cli/src/project_template/
        language: rust
        entry: cargo fmt
        pass_filenames: false
  - repo: https://github.com/instrumentl/pre-commit-just
    rev: v0.1
    hooks:
      - id: format-justfile
        name: "format justfiles"
