[workspace]
members = [
    "flareon",
    "flareon-admin",
    "flareon-auth",
    "flareon-cli",
    "flareon-codegen",
    "flareon-macros",
    # Examples
    "examples/hello-world",
    "examples/todo-list",
    "examples/sessions",
    "examples/admin",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.92"
askama = "0.12.1"
askama_derive = "0.12.5"
askama_parser = "0.2.1"
async-stream = "0.3"
async-trait = "0.1"
axum = "0.7"
backtrace = "0.3"
bytes = "1.7"
cargo_toml = "0.20"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive", "env"] }
clap-verbosity-flag = "2"
convert_case = "0.6"
darling = "0.20"
derive_builder = "0.20"
derive_more = { version = "1", features = ["full"] }
env_logger = "0.11"
fake = { version = "2", features = ["derive", "chrono"] }
flareon = { path = "flareon" }
flareon_codegen = { path = "flareon-codegen" }
flareon_macros = { path = "flareon-macros" }
form_urlencoded = "1"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
glob = "0.3"
hmac = "0.13.0-pre.4"
http = "1.1"
http-body = "1"
http-body-util = "0.1"
indexmap = "2"
itertools = "0.13"
log = "0.4"
mime_guess = "2"
mockall = "0.13"
password-auth = "1.1.0-pre.1"
pin-project-lite = "0.2"
prettyplease = "0.2"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
rand = "0.8"
regex = "1.11"
rustversion = "1"
sea-query = "0.32.0-rc.2"
sea-query-binder = { version = "0.7.0-rc.2", features = ["sqlx-sqlite", "with-chrono", "runtime-tokio"] }
serde = "1"
sha2 = "0.11.0-pre.4"
slug = "0.1"
sqlx = { version = "0.8", default-features = false, features = ["macros", "json", "runtime-tokio", "sqlite", "chrono"] }
subtle = "2"
syn = { version = "2", features = ["full", "extra-traits"] }
sync_wrapper = "1"
thiserror = "1"
time = "0.3.35"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
tower = "0.5.1"
tower-sessions = "0.13"
trybuild = { version = "1", features = ["diff"] }
