services:
  mariadb:
    image: docker.io/mariadb:11
    container_name: cot-mariadb
    environment:
      MARIADB_DATABASE: mysql
      MARIADB_USER: cot
      MARIADB_PASSWORD: cot
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: docker.io/postgres:17-alpine
    container_name: cot-postgres
    environment:
      POSTGRES_USER: cot
      POSTGRES_PASSWORD: cot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: cot-redis
    command: ["redis-server", "--databases", "100"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  webdriver:
    image: docker.io/selenium/standalone-firefox:4.31.0-20250414
    container_name: cot-webdriver
    shm_size: 2gb
    network_mode: host
