[package]
name = "example-sessions"
version = "0.1.0"
publish = false
description = "Sessions - Cot example."
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
askama = "0.14"
cot = { path = "../../cot" }
