[package]
name = "example-todo-list"
version = "0.1.0"
publish = false
description = "TODO List - Cot example."
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
cot = { path = "../../cot" }
