[package]
name = "example-admin"
version = "0.1.0"
publish = false
description = "Admin panel - Cot example."
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
askama = "0.15"
cot = { path = "../../cot", features = ["live-reload"] }
