[resolver]
incompatible-rust-versions = "fallback"

# TODO: Safe to remove once https://github.com/rust-lang/rust/issues/141626 gets resolved.
# Also, see https://github.com/cot-rs/cot/pull/419/changes#r2636869773 for more info.
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-C", "symbol-mangling-version=v0"]
